(function() {var implementors = {};
implementors['glium'] = ["<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glutin/api/egl/ffi/egl/struct.Egl.html' title='glutin::api::egl::ffi::egl::Egl'>Egl</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glutin/api/egl/struct.Context.html' title='glutin::api::egl::Context'>Context</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glutin/api/glx/struct.Context.html' title='glutin::api::glx::Context'>Context</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glutin/api/osmesa/struct.OsMesaContext.html' title='glutin::api::osmesa::OsMesaContext'>OsMesaContext</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glutin/api/x11/ffi/glx_extra/struct.Glx.html' title='glutin::api::x11::ffi::glx_extra::Glx'>Glx</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glutin/api/x11/struct.XWindow.html' title='glutin::api::x11::XWindow'>XWindow</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glutin/api/x11/struct.Window.html' title='glutin::api::x11::Window'>Window</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='glium/struct.LinearSyncFence.html' title='glium::LinearSyncFence'>LinearSyncFence</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='enum' href='glium/enum.Handle.html' title='glium::Handle'>Handle</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
